modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/Horizontal-Panes/issues" #optional
[[mods]] #mandatory
modId="horizontalpanes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Horizontal Panes" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/CodenameRevy/Horizontal-Panes" #optional
logoFile="horizontalpanes.png" #optional
credits="CodenameRevy" #optional
authors="CodenameRevy" #optional
description='''
Adds Horizontal Glass Panes to the game.
'''
[[dependencies.horizontalpanes]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.horizontalpanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
