modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/Horizontal-Panes/issues" #optional
[[mods]] #mandatory
modId="horizontalpanes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Horizontal Glass Panes" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/CodenameRevy/Horizontal-Panes" #optional
#logoFile="horizontalpanes.png" #optional
credits="CodenameRevy" #optional
authors="CodenameRevy" #optional
description='''
1.15.2 port.
Adds Horizontal Glass Panes to the game.
'''

[[dependencies.horizontalpanes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.horizontalpanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
